name: Tag-based Build Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (qa or prod)"
        required: true
        default: "qa"
      tag:
        description: "Image tag to deploy"
        required: true

jobs:
  build:
    name: Build and Push Docker Image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.BUILD_AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.BUILD_AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.BUILD_ECR_REGISTRY }}

      - name: Build, Tag, and Push Docker Image
        run: |
          TAG="${GITHUB_REF##*/}"   # e.g. v1.0.0
          IMAGE_URI="${{ secrets.BUILD_ECR_REGISTRY }}/${{ secrets.BUILD_ECR_REPOSITORY }}:$TAG"

          echo "Building image: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          docker rmi $IMAGE_URI
