name: Tag-based Build Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (qa or prod)"
        required: true
        default: "qa"
      tag:
        description: "Image tag to deploy"
        required: true

jobs:
  build:
    name: Build and Push Docker Image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_ACCOUNT }}

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REPOSITORY: ${{ secrets.BUILD_ECR_REGISTRY }}
        run: |
          TAG="${GITHUB_REF##*/}"
          docker build -t $ECR_REPOSITORY:$TAG .
          docker push $ECR_REPOSITORY:$TAG
          docker rmi $ECR_REPOSITORY:$TAG
