name: Deploy Tracking Service to AWS EKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (qa or prod)"
        required: true
        default: "qa"
      tag:
        description: "Image tag to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate environment input
        run: |
          ENV="${{ github.event.inputs.environment }}"
          if [[ "$ENV" != "qa" && "$ENV" != "prod" ]]; then
            echo "Error: Invalid environment '$ENV'. Must be 'qa' or 'prod'."
            exit 1
          fi
          echo "ENVIRONMENT=$ENV" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create manifest directory
        run: mkdir -p manifest

      - name: Generate ConfigMap YAML
        env:
          ENV_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        run: echo "$ENV_CONTENT" > manifest/configmap.yaml

      - name: Set environment-specific variables
        run: |
          if [ "$ENVIRONMENT" == "prod" ]; then
            EKS_CLUSTER_NAME="${{ secrets.EKS_CLUSTER_NAME_PROD }}"
            ECR_REPOSITORY="${{ secrets.ECR_REPOSITORY_PROD }}"
            NAMESPACE="default"
          else
            EKS_CLUSTER_NAME="${{ secrets.EKS_CLUSTER_NAME_QA }}"
            ECR_REPOSITORY="${{ secrets.ECR_REPOSITORY_QA }}"
            NAMESPACE="microservices-qa"
          fi

          # Fail fast if any variable is empty
          if [ -z "$EKS_CLUSTER_NAME" ] || [ -z "$ECR_REPOSITORY" ] || [ -z "$NAMESPACE" ]; then
            echo "Error: One of the environment variables is missing!"
            exit 1
          fi

          FULL_IMAGE="$ECR_REPOSITORY:${{ github.event.inputs.tag }}"

          echo "EKS_CLUSTER_NAME=$EKS_CLUSTER_NAME" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
          echo "FULL_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV

      - name: Update deployment manifest
        run: |
          envsubst < manifest/tracking-service.yaml > manifest/tracking-service-updated.yaml
          sed -i "s|REPLACE_IMAGE|${FULL_IMAGE}|g" manifest/tracking-service-updated.yaml

      - name: Deploy to AWS EKS
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ${{ secrets.AWS_REGION }}
          kubectl apply -f manifest/tracking-service-updated.yaml -n $NAMESPACE
          kubectl apply -f manifest/configmap.yaml -n $NAMESPACE
          sleep 10
          kubectl get pods -n $NAMESPACE | grep tracking
